### ISSUE TITLE
Locations in final products are not filled

### ISSUE THREAD

**Issue by zwjsoft** [qcadoo/mes#56]
When technologies accept,There are some error hints.Locations in final products are not filled.But in Material flow Tab,Final Products Loaction  is not editable.

**Comment by alkozyra** [comment]
You need to select 'Components location' and 'Products input location'. Then click 'Fill locations in components'. Locations for components and final product will be filled and you will be able to accept your technology.

**Comment by Oddward** [comment]
Is this issue really solved? Or closed coz no reply?
It seems like the Location fields cannot be edited when the **Range** tab is set to "_many divisions_" instead of "_one division_" (i.e. if the production line is not all within the same division). Is this by design? It doesn't seem right.
We cannot have a technology that uses workstations under different divisions?

Also, thanks for the tip about clicking "Fill locations...", but how were we supposed to figure that out lol (it's not in docs).
